### ISSUE TITLE
source good but download... trojan

### ISSUE THREAD

**Issue by P5yl0** [osjoberg/MceRemoteMapper#1]
*lol*

source compiled and everything okay...^^
but the download...

Windows Defender gives...
Trojan:Win32/Rundas.B

**Comment by osjoberg** [comment]
Thank you for reporting the issue. I do belive the warning where a false positive. But it is better to be safe than sorry, and it would hinder people to run the application. So I've replaced the old upload with a new version.

https://www.virustotal.com/#/file/e9eff26b40848fc8dd6b7676bae71429b8a5752e759c40f47a801efad2a70ec0/detection

**Comment by P5yl0** [comment]
yeah i thaught the same first... 
but after i compiled the source the file had no warnings....
downloaded your upload for a recheck and theres no warning too
so maybe it was inficted... now its good... ^^
and thnx for your work...
